// // reducer.js
// import { SEND_JSON_DATA } from './action';

// const initialState = {
//   jsonData: null,
// };

// const reducer = (state = initialState, action) => {
//   switch (action.type) {
//     case SEND_JSON_DATA:
//       return {
//         ...state,
//         jsonData: action.payload,
//       };
//     default:
//       return state;
//   }
// };

// export default reducer;

import {createReducer} from '@reduxjs/toolkit';

const initialState = "";

export const selectedRow_reducer = createReducer(initialState, (builder) => {
  builder
    .addCase("getData_action", (state,action) => {
        console.log("running this reducer")
        console.log("action.payload : ", action.payload)
      return state  = action.payload
    })
    
    .addDefaultCase((state) => state);
});


const initialState1 = "";

export const selectedTime_reducer = createReducer(initialState1, (builder) => {
  builder
    .addCase("getData_action1", (state,action) => {
        console.log("running this second reducer")
        console.log("action.payload : ", action.payload)
      return state  = action.payload
    })
    
    .addDefaultCase((state) => state);
});






// .addCase("getData_action1",(state,action)=>{
//     console.log("running second reducer")
//     console.log("action.payload : ", action.payload)
//     return state  = action.payload
// })

// "use client";

// import { createReducer } from "@reduxjs/toolkit";

// const initialState = 49;

// export const changeValueReducer = createReducer(initialState, (builder) => {
//   builder
//     .addCase("increment", (state) => {
//       return state + 1;
//     })
//     .addCase("decrement", (state) => {
//       return state - 1;
//     })
//     .addCase("incrementByPayload", (state, action) => {
//       return state + action.payload;
//     })
//     .addDefaultCase((state) => state);
// });

// Store file : 
// 'use client';

// import { configureStore } from "@reduxjs/toolkit";
// import { changeValueReducer } from "./reducers";

// export const store = configureStore({
//   reducer: {
//     changeValueReducer,
//   },
// });

// Provider use : 
// "use client";

// import { Provider } from "react-redux";
// import "./globals.css";
// import { Inter } from "next/font/google";
// import { store } from "./redux/store";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <Provider store={store}>
//         <body className={inter.className}>{children}</body>
//       </Provider>
//     </html>
//   );
// }

// Page .js file : 

// "use client";

// import React from "react";
// import { useDispatch } from "react-redux";

// const page = () => {
//   const value = 20;
//   const dispatch = useDispatch();
//   return (
//     <div className="w-full h-screen flex items-center justify-center gap-20">
//       {value}
//       <button
//         onClick={() =>
//           dispatch({
//             type: "increment",
//           })
//         }
//         className="bg-red-500 px-10 py-3 text-2xl text-black"
//       >
//         Increment
//       </button>
//       <button
//         onClick={() =>
//           dispatch({
//             type: "decrement",
//           })
//         }
//         className="bg-red-500 px-10 py-3 text-2xl text-black"
//       >
//         Increment
//       </button>
//       <button
//         onClick={() =>
//           dispatch({
//             type: "incrementByPayload",
//             payload: 5,
//           })
//         }
//         className="bg-red-500 px-10 py-3 text-2xl text-black"
//       >
//         Increment by payload and payload is 5
//       </button>
//     </div>
//   );
// };

// export default page;